name: CI

on: push

jobs:
  build:

    # TODO Consider running on macos-latest as well.
    runs-on: ubuntu-latest
    # Just in case we start having to pay for our CI compute costs, it's probably wise
    # to have a time limit.
    timeout-minutes: 60
    strategy:
      # Keep running all test configurations, even if one of them fails. This is helpful
      # because if one configuration fails, it's useful to see whether the other ones
      # fail too. (This helps diagnose tests that are flaky or specific to one Python
      # version.)
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install graphviz
        pip install --upgrade --upgrade-strategy eager '.[dev]'
        # This prints out all installed package versions, which may help for debugging
        # build failures.
        pip freeze
    - name: Lint with flake8 and black
      run: |
        flake8
        black --check .
    - name: Test with pytest
      run: |
        pytest --parallel --slow
